/* Solar system bodies — ported verbatim from the design prototype.
   Stats are in "freedom units" (miles / °F) and the blurbs are deliberately funny. */
window.SOLAR_DATA = [
  { key: 'sun', name: 'Sun', type: 'G-type Main-Sequence Star', color: '#ffb31c', tagline: 'Local star · est. 4.6 Gyr', radius: 8, dist: 0, tex: 'sun', sun: true,
    blurb: 'Absolutely refuses to let anything else be the center of attention, and has the gravity to back it up. Holds 99.86% of all the mass in the entire solar system and still shows up to work every single day. Please do not look directly at it; it does not enjoy being perceived.',
    stats: [['Diameter', '865,000 mi'], ['Surface temp', '9,940 °F'], ['Share of system mass', '99.86%'], ['Light to Earth', '8 min 20 s'], ['Age', '~4.6 billion yrs']] },
  { key: 'mercury', name: 'Mercury', type: 'Terrestrial Planet', color: '#9a8a73', tagline: 'Closest to the Sun', radius: 0.62, dist: 15, tex: 'rock',
    blurb: 'Smallest planet, biggest mood swings: 806 °F by day and minus 292 °F by night, because there is no atmosphere to hold heat — or a grudge. Closest to the Sun and yet somehow still the most emotionally distant.',
    stats: [['Diameter', '3,032 mi'], ['From Sun', '36M mi'], ['A year here', '88 days'], ['A day here', '59 days'], ['Moons', '0 (forever alone)']] },
  { key: 'venus', name: 'Venus', type: 'Terrestrial Planet', color: '#e3b76a', tagline: 'The hot one', radius: 1.05, dist: 21, tex: 'venus',
    blurb: 'Earth’s “twin,” if your twin were a 869 °F pressure cooker that rains sulfuric acid and spins backwards out of pure spite. A single day here is longer than its entire year, which is frankly a scheduling nightmare.',
    stats: [['Diameter', '7,521 mi'], ['From Sun', '67M mi'], ['A year here', '225 days'], ['A day here', '243 days (!)'], ['Moons', '0']] },
  { key: 'earth', name: 'Earth', type: 'Terrestrial Planet', color: '#3b7fc4', tagline: 'You are here', radius: 1.1, dist: 28, tex: 'earth', moon: true,
    blurb: 'The only known planet with pizza, oceans, and a comments section. 71% water, 100% drama, and currently the sole confirmed address for life, taxes, and people who reply-all. Mostly harmless.',
    stats: [['Diameter', '7,918 mi'], ['From Sun', '93M mi'], ['A year here', '365.25 days'], ['A day here', '24 hours'], ['Moons', '1 (very loyal)']] },
  { key: 'moon', name: 'The Moon', type: 'Natural Satellite', color: '#c9c9cf', tagline: 'Earth’s plus-one', radius: 0.3, dist: 0, moonOf: 'earth', tex: 'rock',
    blurb: 'Earth’s emotional support rock. Personally responsible for ocean tides, werewolves, and roughly half of all poetry ever written. Shows us the same face forever because it is tidally locked — not because it is shy.',
    stats: [['Diameter', '2,159 mi'], ['From Earth', '238,900 mi'], ['Orbit', '27.3 days'], ['Gravity', '1/6 of Earth’s'], ['Vibe', 'Quietly supportive']] },
  { key: 'mars', name: 'Mars', type: 'Terrestrial Planet', color: '#c0461f', tagline: 'The fixer-upper', radius: 0.66, dist: 36, tex: 'mars',
    blurb: 'Great views, two potato-shaped moons, and absolutely no atmosphere — literally. A promising fixer-upper that is rusty all over because it never once got the oxygen memo. Real estate prices expected to skyrocket any decade now.',
    stats: [['Diameter', '4,212 mi'], ['From Sun', '142M mi'], ['A year here', '687 days'], ['A day here', '24.6 hours'], ['Moons', '2 (both potatoes)']] },
  { key: 'belt', name: 'Asteroid Belt', type: 'Circumstellar Disc', color: '#8d8278', tagline: 'Mars ↔ Jupiter', radius: 0, dist: 46, belt: true,
    blurb: 'Not the dense, ship-crunching maze the movies promised — it is mostly empty space with the occasional lonely pebble. The leftover crumbs of a planet that never quite came together. Deeply relatable, honestly.',
    stats: [['Location', '204–297M mi'], ['Members', 'Millions+'], ['Total mass', '< 4% of the Moon'], ['Largest', 'Ceres (584 mi)'], ['Density', 'Disappointingly sparse']] },
  { key: 'jupiter', name: 'Jupiter', type: 'Gas Giant', color: '#d8a06a', tagline: 'The big one', radius: 3.4, dist: 62, tex: 'jupiter',
    blurb: 'The big sibling who catches the comets so the inner planets do not have to. Sporting a 350-year-old storm that is wider than the entire Earth, because of course it is. Has 95+ moons and counting; commitment is clearly not the issue here.',
    stats: [['Diameter', '86,900 mi'], ['From Sun', '484M mi'], ['A year here', '11.9 years'], ['A day here', '9.9 hours'], ['Moons', '95+']] },
  { key: 'saturn', name: 'Saturn', type: 'Gas Giant', color: '#e6c98f', tagline: 'Put a ring on it', radius: 2.9, dist: 84, tex: 'saturn', rings: true,
    blurb: 'Put a ring on it — several, actually — all made of ice and rock and showing absolutely everyone up. So low in density that it would float in a bathtub, assuming you could find one roughly 75,000 mi wide.',
    stats: [['Diameter', '72,400 mi'], ['From Sun', '888M mi'], ['A year here', '29.4 years'], ['A day here', '10.7 hours'], ['Moons', '146+']] },
  { key: 'uranus', name: 'Uranus', type: 'Ice Giant', color: '#a6e1e6', tagline: 'The sideways one', radius: 1.9, dist: 104, tex: 'uranus', rings: true,
    blurb: 'Rolls around the Sun lying completely on its side, because why not. Reportedly smells faintly of rotten eggs, thanks to hydrogen sulfide in its clouds — science’s words, not ours. We are not going to make the joke. You are welcome.',
    stats: [['Diameter', '31,500 mi'], ['From Sun', '1.78B mi'], ['A year here', '84 years'], ['A day here', '17 hours'], ['Moons', '28']] },
  { key: 'neptune', name: 'Neptune', type: 'Ice Giant', color: '#3a64d6', tagline: 'The windy one', radius: 1.85, dist: 122, tex: 'neptune',
    blurb: 'The windiest place in the solar system, with 1,300 mph gales howling across a planet almost nobody ever visits. Discovered by math before anyone actually pointed a telescope at it — the original “trust me, it is out there.”',
    stats: [['Diameter', '30,600 mi'], ['From Sun', '2.8B mi'], ['A year here', '165 years'], ['A day here', '16 hours'], ['Moons', '16']] },
  { key: 'pluto', name: 'Pluto', type: 'Dwarf Planet*', color: '#cdb89c', tagline: '*citation needed', radius: 0.34, dist: 138, tex: 'pluto', incl: 0.12,
    blurb: 'Planet (2006, colorized). Demoted to “dwarf planet” by a committee meeting it was not even invited to. Still out here, 3.7 billion mi from home, orbiting quietly with a giant heart-shaped glacier on its face — a bigger person than all of us. We stan.',
    stats: [['Diameter', '1,477 mi'], ['From Sun', '3.7B mi'], ['A year here', '248 years'], ['A day here', '6.4 days'], ['Status', 'Planet (it’s fine, we’re fine)']] }
];
