/* Rotating ticker pool — legendary quotes + mind-bending facts.
   Ported verbatim from the design prototype. */
window.SOLAR_FACTS = [
  { tag: 'CARL SAGAN', text: '“Somewhere, something incredible is waiting to be known.”' },
  { tag: 'NEIL ARMSTRONG', text: '“That’s one small step for man, one giant leap for mankind.”' },
  { tag: 'CARL SAGAN', text: '“We are made of star-stuff.”' },
  { tag: 'STEPHEN HAWKING', text: '“Look up at the stars and not down at your feet.”' },
  { tag: 'ARTHUR C. CLARKE', text: '“Two possibilities exist: either we are alone in the Universe or we are not. Both are equally terrifying.”' },
  { tag: 'NEIL deGRASSE TYSON', text: '“The universe is under no obligation to make sense to you.”' },
  { tag: 'K. TSIOLKOVSKY', text: '“Earth is the cradle of humanity, but one cannot live in the cradle forever.”' },
  { tag: 'CARL SAGAN', text: '“For small creatures such as we the vastness is bearable only through love.”' },
  { tag: 'OSCAR WILDE', text: '“We are all in the gutter, but some of us are looking at the stars.”' },
  { tag: 'PLATO', text: '“Astronomy compels the soul to look upward.”' },
  { tag: 'CARL SAGAN', text: '“The cosmos is within us. We are a way for the universe to know itself.”' },
  { tag: 'YURI GAGARIN', text: '“Orbiting Earth, I saw how beautiful our planet is. Let us preserve and increase this beauty, not destroy it.”' },
  { tag: 'EDWIN HUBBLE', text: '“Equipped with his five senses, man explores the universe around him and calls the adventure science.”' },
  { tag: 'DID YOU KNOW', text: 'A day on Venus is longer than an entire year on Venus.' },
  { tag: 'COSMIC SCALE', text: 'There are more stars in the universe than grains of sand on every beach on Earth.' },
  { tag: 'TRUE STORY', text: 'Saturn is so light it would float — if only you could find a bathtub big enough.' },
  { tag: 'DID YOU KNOW', text: 'It rains diamonds in the deep skies of Neptune and Uranus.' },
  { tag: 'DEEP SPACE', text: 'Voyager 1, launched in 1977, now drifts through interstellar space — our farthest emissary.' },
  { tag: 'COSMIC SCALE', text: 'You could fit about 1.3 million Earths inside the Sun.' },
  { tag: 'DID YOU KNOW', text: 'The footprints on the Moon may last millions of years — there is no wind to erase them.' },
  { tag: 'MIND-BENDER', text: 'A single teaspoon of neutron star would weigh about a billion tons.' },
  { tag: 'TRUE STORY', text: 'Space is completely silent. With no air to carry it, sound has nowhere to go.' },
  { tag: 'DID YOU KNOW', text: 'Olympus Mons on Mars stands nearly three times the height of Mount Everest.' },
  { tag: 'COSMIC FACT', text: 'Every atom of gold on Earth was forged in the heart of an exploding star.' },
  { tag: 'THE LONG GAME', text: 'In about 4 billion years, the Milky Way will collide with the Andromeda galaxy.' },
  { tag: 'COSMIC SCALE', text: 'The observable universe spans roughly 93 billion light-years.' },
  { tag: 'DID YOU KNOW', text: 'Sunlight takes 8 minutes and 20 seconds to travel from the Sun to your eyes.' },
  { tag: 'MIND-BENDER', text: 'In the vacuum of space, two pieces of the same metal can weld together on contact.' },
  { tag: 'TRUE STORY', text: 'Jupiter’s Great Red Spot is a storm wider than Earth that has raged for centuries.' },
  { tag: 'DEEP FREEZE', text: 'The coldest known place in the universe is the Boomerang Nebula, at -458 °F.' },
  { tag: 'DID YOU KNOW', text: 'Mercury and Venus are the only planets with no moons of their own.' },
  { tag: 'COSMIC SCALE', text: 'The largest known star, UY Scuti, could swallow billions of Suns.' },
  { tag: 'TREASURE', text: 'The scorching planet 55 Cancri e may be made largely of diamond.' },
  { tag: 'DID YOU KNOW', text: 'A whole year on Mercury lasts just 88 Earth days.' },
  { tag: 'CARL SAGAN', text: '“The nitrogen in our DNA, the calcium in our teeth, the iron in our blood were made in the interiors of collapsing stars.”' },
  { tag: 'KONSTANTIN TSIOLKOVSKY', text: '“The Earth is the cradle of the mind, but we cannot live forever in a cradle.”' },
  { tag: 'CHRISTA McAULIFFE', text: '“I touch the future. I teach.”' },
  { tag: 'CARL SAGAN', text: '“Imagination will often carry us to worlds that never were. But without it, we go nowhere.”' },
  { tag: 'SALLY RIDE', text: '“The stars don’t look bigger, but they do look brighter.”' },
  { tag: 'GALILEO GALILEI', text: '“The Sun, with all those planets revolving around it, can still ripen a bunch of grapes as if it had nothing else to do.”' },
  { tag: 'JOHANNES KEPLER', text: '“I used to measure the heavens; now I measure the shadows of Earth.”' },
  { tag: 'EUGENE CERNAN', text: '“We leave as we came and, God willing, as we shall return: with peace and hope for all mankind.”' },
  { tag: 'WERNHER VON BRAUN', text: '“I have learned to use the word impossible with the greatest caution.”' },
  { tag: 'RAY BRADBURY', text: '“The universe is full of magical things patiently waiting for our wits to grow sharper.”' },
  { tag: 'NEIL deGRASSE TYSON', text: '“We are part of this universe; we are in this universe, but perhaps more important, the universe is in us.”' },
  { tag: 'BUZZ ALDRIN', text: '“Magnificent desolation.”' },
  { tag: 'STEPHEN HAWKING', text: '“Remember to look up at the stars and not down at your feet. Be curious.”' },
  { tag: 'COSMIC SCALE', text: 'If the Sun were the size of a front door, Earth would be the size of a nickel about 80 feet away.' },
  { tag: 'MIND-BENDER', text: 'The light you see from the Andromeda galaxy left it 2.5 million years ago.' },
  { tag: 'DID YOU KNOW', text: 'There are likely more trees on Earth than stars in the Milky Way — but far more stars in the universe than trees.' },
  { tag: 'TRUE STORY', text: 'A full NASA spacesuit costs roughly the same as a small house — about $12 million.' },
  { tag: 'COSMIC FACT', text: 'The Sun makes up 99.86% of all the mass in the solar system.' },
  { tag: 'DEEP SPACE', text: 'A golden record bolted to Voyager carries greetings in 55 languages, drifting for the next billion years.' },
  { tag: 'MIND-BENDER', text: 'If you fell into a black hole, an outside observer would see you frozen forever at its edge.' },
  { tag: 'DID YOU KNOW', text: 'Neutron stars can spin up to 700 times every single second.' },
  { tag: 'COSMIC SCALE', text: 'The Milky Way is so wide that light takes 100,000 years to cross it.' },
  { tag: 'TRUE STORY', text: 'Astronauts can grow up to two inches taller in space as their spines decompress.' },
  { tag: 'DID YOU KNOW', text: 'The Moon is slowly drifting away from Earth, about 1.5 inches farther every year.' },
  { tag: 'MIND-BENDER', text: 'There may be a planet made of diamond, twice the size of Earth, orbiting a nearby pulsar.' },
  { tag: 'COSMIC FACT', text: 'More energy from the Sun hits Earth every hour than humanity uses in an entire year.' },
  { tag: 'TRUE STORY', text: 'The International Space Station orbits Earth roughly every 90 minutes — 16 sunrises a day.' },
  { tag: 'DEEP TIME', text: 'The Sun has about 5 billion years of fuel left before it swells into a red giant.' },
  { tag: 'DID YOU KNOW', text: 'Space isn’t totally empty — every cubic meter holds a few hydrogen atoms.' },
  { tag: 'COSMIC SCALE', text: 'Light from the Sun takes 5.5 hours to reach Pluto.' },
  { tag: 'MIND-BENDER', text: 'Because looking out is looking back in time, telescopes are essentially time machines.' }
];
